
CFLAGS = -0 -mt -wx -lr -we -ox

all: erlev.com upcase.com hackz.com

erlev.com: erlev.c
	*wcl $(CFLAGS) $<

upcase.com: upcase.c
	*wcl $(CFLAGS) $<

hackz.com: hackz.c
	*wcl $(CFLAGS) $<
