@ECHO OFF

SET MORVER=2023.0

A72 MORE.A72 MORE.COM
IF ERRORLEVEL 1 GOTO FAIL

ECHO.

IF EXIST MORE.ZIP DEL MORE.ZIP
IF EXIST MORE_SRC.ZIP DEL MORE_SRC.ZIP

ECHO BUILDING MORE %MORVER% ZIP AND SVP PACKAGES...

ZIP -9 -qkrDX MORE.ZIP MORE.COM MORE.TXT
ZIP -9 -qkrDX MORE_SRC.ZIP BUILD.BAT MORE.A72 MORE.TXT

:: BUILD THE SVP PACKAGE
MKDIR BIN
MKDIR APPINFO
MKDIR DOC
MKDIR DOC\MORE

COPY MORE.COM BIN\ > NUL
COPY MORE.TXT DOC\MORE\ > NUL
ECHO VERSION: %MORVER%>> APPINFO\MORE.LSM
ECHO DESCRIPTION: displays output one screen at a time>> APPINFO\MORE.LSM

ZIP -9 -qkrDX -m MORE.SVP APPINFO BIN DOC

RMDIR APPINFO
RMDIR BIN
RMDIR DOC\MORE
RMDIR DOC

ECHO ALL DONE

GOTO KONIEC

:FAIL
ECHO ERROR OCCURRED

:KONIEC
