/* DO NOT EDIT THIS FILE, IT IS AUTO-GENERATED BY LOCALES.EXE */
char *kblayouts[] = {
  /****** EN ******/
  "English (US)\0en\0\1\265\0\0\0\0",
  "English (UK)\0uk\0\1\265\0\1\0\0",
  /****** HY ******/
  "Armenian\0hy\0\3\203\6\3\0\0",
  /****** BG ******/
  "Bulgarian\0bg\0\3\150\3\2\0\0",
  /****** FR ******/
  "French (France)\0fr\0\3\132\1\1\0\0",
  "French (Canada, standard)\0cf\0\3\137\11\1\0\0",
  "French (Canada, legacy)\0cf\0\3\137\11\1\1\365",
  /****** DE ******/
  "German\0de\0\3\132\1\1\0\0",
  /****** HU ******/
  "Hungarian\0hu\0\3\124\1\1\0\320",
  /****** IT ******/
  "Italian\0it\0\3\132\1\1\0\0",
  /****** NO ******/
  "Norvegian\0no\0\3\132\11\1\0\0",
  /****** PL ******/
  "Polish (Programmer)\0pl\0\3\337\12\1\0\0",
  "Polish (Typewriter)\0pl\0\3\337\12\1\0\326",
  /****** RU ******/
  "Russian (Standard)\0ru\0\3\142\3\2\0\0",
  "Russian (Typewriter)\0ru\0\3\142\3\2\1\273",
  /****** SL ******/
  "Slovenian\0si\0\3\124\1\1\0\0",
  /****** ES ******/
  "Spanish\0es\0\3\132\1\1\0\0",
  /****** SV ******/
  "Swedish\0sv\0\3\132\1\1\0\0",
  /****** TR ******/
  "Turkish\0tr\0\3\131\1\2\0\0",
  NULL};
