#define OFFLOC_EN 0
#define OFFLEN_EN 2
#define OFFLOC_FR 2
#define OFFLEN_FR 3
#define OFFLOC_DE 5
#define OFFLEN_DE 1
#define OFFLOC_PL 6
#define OFFLEN_PL 1
#define OFFLOC_ES 7
#define OFFLEN_ES 1
#define OFFLOC_TR 8
#define OFFLEN_TR 1
#define OFFCOUNT 9
