/* DO NOT EDIT THIS FILE, IT IS AUTO-GENERATED BY LOCALES.EXE */
#define OFFLOC_EN 0
#define OFFLEN_EN 2
#define OFFLOC_FR 2
#define OFFLEN_FR 3
#define OFFLOC_DE 5
#define OFFLEN_DE 1
#define OFFLOC_HU 6
#define OFFLEN_HU 1
#define OFFLOC_PL 7
#define OFFLEN_PL 1
#define OFFLOC_RU 8
#define OFFLEN_RU 2
#define OFFLOC_ES 10
#define OFFLEN_ES 1
#define OFFLOC_TR 11
#define OFFLEN_TR 1
#define OFFCOUNT 12
