@ECHO OFF
SET DOSDIR=C:\FREEDOS
PATH A:\;%DOSDIR%\BIN
SET NLSPATH=%DOSDIR%\NLS
SET TEMP=C:\TEMP
PROMPT $P$G
SET DIRCMD=/P /OGN /4
SET FDNPKG.CFG=A:\FDNPKG.CFG
ALIAS REBOOT=FDAPM COLDBOOT
ALIAS HALT=FDAPM POWEROFF
CALL A:\RAMDISK.BAT
CALL A:\CDROM.BAT
A:\FDAPM APMDOS
ECHO.
ECHO *** Welcome to Svarog386 ***
ECHO.
IF NOT EXIST CDROM001 ECHO ERROR: UNSUPPORTED CDROM DRIVE.
IF EXIST CDROM001 INSTALL

