@ECHO OFF
SET DOSDIR=C:\FREEDOS
PATH A:\;%DOSDIR%\BIN
SET NLSPATH=%DOSDIR%\NLS
SET TEMP=C:\TEMP
PROMPT $P$G
SET DIRCMD=/P /OGN /4
SET FDNPKG.CFG=A:\FDNPKG.CFG
ALIAS REBOOT=FDAPM COLDBOOT
ALIAS HALT=FDAPM POWEROFF

REM *** CDROM initialization ***
IF NOT EXIST FDCD0001 DEVLOAD /Q /H A:\ELTORITO.SYS /D:FDCD0001
IF NOT EXIST FDCD0001 DEVLOAD /Q /H A:\UDVD2.SYS /D:FDCD0001 /H
IF EXIST FDCD0001 SHSUCDX /D:FDCD0001,X /Q

A:\FDAPM APMDOS
ECHO.
ECHO *** Welcome to Svarog386 ***
ECHO.
IF NOT EXIST FDCD0001 ECHO ERROR: UNSUPPORTED CDROM DRIVE.
IF EXIST FDCD0001 INSTALL
