@ECHO OFF

MKDIR NLS

REM copy english translations as-is
COPY LANG\ENGLISH.TXT NLS\SVARCOM.EN

REM GENERATE CODEPAGE-SPECIFIG VERSIONS OUT OF UTF-8 FILES
utf8tocp 850 LANG\FRENCH.TXT > NLS\SVARCOM.FR
utf8tocp maz LANG\POLISH.TXT > NLS\SVARCOM.PL

REM COMPILE ALL RESOURCES TOGETHER
tlumacz en fr pl

REM CLEAN UP
DEL NLS\SVARCOM.*
RMDIR NLS
